### PR TITLE
Add sim compatibility for CTRE libraries on MacOS

### PR DESCRIPTION
**Pull request by AndrewLester**

### CODE REVIEW

**Review by ErikBoesen — APPROVED** [review]

**Comment by ErikBoesen** [comment]
This looks alright, but might it be preferable to add this as a git submodule or some such implementation rather than copying all the code directly?

**Comment by AndrewLester** [comment]
> This looks alright, but might it be preferable to add this as a git submodule or some such implementation rather than copying all the code directly?

Yeah that's a good idea. I want to be careful with this code though, it's straight from decompiling rev and ctre libraries.

**Comment by ArchdukeTim** [comment]
@AndrewLester was anything changed? What compatibility was missing that this adds?

**Comment by AndrewLester** [comment]
> @AndrewLester was anything changed? What compatibility was missing that this adds?

Essentially what it does is remove any reference to JNI classes in the normal CTRE libraries. The JNI classes try to load binaries that aren't available for MacOS, crashing the sim. This code just prevents those crashes so we can use the sim for other things.

**Pull request merged**
